[package]
name = "rust-aoc-2021"
version = "0.1.0"
edition = "2021"
default-run = "day02"

[[bin]]
name = "day01"
path = "src/day01.rs"


[[bin]]
name="day02"
path = "src/day02.rs"

[dependencies]
regex = "1"